#pragma once
#include <appframe.h>
#include "LKAclass.h"
#include "SANclass.h"
#include "Player.h"
#include "Damage.h"
#include "timer.h"
#include "PlayerBomb.h"
#include "SanBomb.h"
#include "LkaBomb.h"
#include "ModeGame.h"
#include "ApplicationMain.h"
#include "ModeBoss.h"
#include "ModeEnding.h"
#include "ModeGameOver.h"
#include "ModeLogo.h"
#include "ModeStage0.h"
#include "ModeStage1.h"
#include "ModeStage2.h"
#include "ModeStage3.h"
#include "ModeTitle.h"

#include <string>
#include <memory>
#include <vector>

#include <iostream>
#include <fstream>
#include <sstream>
#include <DxLib.h>
